# Generated by Django 4.2.7 on 2023-11-22 02:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='userID',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIK', models.CharField(max_length=50)),
                ('NPWP', models.CharField(max_length=50)),
                ('BankAccount', models.CharField(max_length=50)),
                ('BankName', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.accountuser')),
            ],
        ),
    ]
