# Generated by Django 4.2.7 on 2023-11-22 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_accountuser_is_staff_alter_accountuser_userid_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dadName', models.CharField(max_length=50)),
                ('momName', models.CharField(max_length=50)),
                ('dadJob', models.CharField(max_length=20)),
                ('momJob', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.accountuser')),
            ],
        ),
    ]
