# Generated by Django 4.2.7 on 2023-11-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_accountuser_is_child_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
