# Generated by Django 5.0 on 2023-12-12 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_accountuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='AccountUser',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
